version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Debug
clone_folder: c:\Projects\ClassicAssist\
init:
- ps: >-
    git config --global credential.helper store

    Add-Content "$HOME\.git-credentials" "https://$($env:githubtoken):x-oauth-basic@github.com`n"

    git config --global user.email "reeeetus@gmail.com"

    git config --global user.name "Reetus"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(full_version)
  file_version: $(full_version)
environment:
  githubtoken:
    secure: xIXqJg4atQ4QWCrvSU0ar/eFXWujui0MG8+gijwdx8+IF+5Lg/QkftiLawcT5pzg
before_build:
- ps: >-
    $d = [datetime]"7/3/2020 00:00"

    $sd = Get-Date

    $env:version = [math]::floor((New-TimeSpan -Start $d -End $sd).TotalDays)

    $env:full_version = "0.3.$env:version.$env:APPVEYOR_BUILD_NUMBER"

    Update-AppveyorBuild -Version "$env:full_version"

    nuget restore
build:
  project: ClassicAssist.sln
  verbosity: minimal
after_build:
- ps: >-
    cd Output\net48

    .\ExportCommands.exe c:\Projects\ClassicAssist\Output\net48\ClassicAssist.dll

    del ExportCommands.*


    $files = (Get-ChildItem . -Recurse  | Resolve-Path -Relative)


    $filespsobject = @()


    foreach ( $file in $files )

    {
        $f = Get-ItemProperty $file

        if (!($f -is [System.IO.DirectoryInfo]))
        {
            $item = "" | select Name, Size, ModifiedDate, SHA1
            $item.Name = ($file) -replace "\.\\",""
            $item.Size = $f.Length
            $item.SHA1 =  (get-filehash -path $f.FullName -Algorithm sha1).Hash
            $item.ModifiedDate = $f.LastWriteTime.ToString("o")
            $filespsobject += $item
        }

        $json = $filespsobject | convertto-json
    }


    $json | Out-File MANIFEST.json


    cd ..\..\..

    & cmd /c 'git clone https://github.com/Reetus/ClassicAssist.wiki.git 2>&1'

    cd ClassicAssist.wiki

    copy ..\ClassicAssist\Output\net48\Docs\*.md .

    & cmd /c 'git add *'

    & cmd /c 'git commit -a -m "Update Wiki" 2>&1'

    & cmd /c 'git push 2>&1'
artifacts:
- path: Output\net48
  name: ClassicAssist
deploy:
- provider: GitHub
  tag: $(full_version)
  auth_token:
    secure: mJWk62zhXmBw0jG3EpII0T9CIaS1qwLQGcvc6QJjagGLN+cokd1xOAHIszD1jnc9
  prerelease: false
  on:
    branch: master
on_success:
- cmd: dir c:\Projects\ClassicAssist\Output\net48\